platform :ios, '10.0'

target 'one' do
  use_frameworks!

  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'FastImageCache'
  pod 'KILabel'
  pod 'CocoaLumberjack/Swift'

end
