# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'one' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for one
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'FastImageCache'

end
